/* Create database and use it for subsequent commands */
CREATE DATABASE IF NOT EXISTS BRAND_CENTRAL;
USE BRAND_CENTRAL;

/* Setup tables for database. */

/* Tables for students and meetings. */
CREATE TABLE IF NOT EXISTS USER (
    USER_ID        INTEGER(8) UNIQUE NOT NULL AUTO_INCREMENT,
    USERNAME       VARCHAR(35) NOT NULL,
    USER_LNAME     VARCHAR(35) NOT NULL,
    USER_FNAME     VARCHAR(35) NOT NULL,
    USER_EMAIL     VARCHAR(35) UNIQUE NOT NULL,
    USER_PASS_HASH VARCHAR(100) NOT NULL,
    USER_PICT_URL  VARCHAR(100) DEFAULT NULL,
    LAST_SEEN      DATETIME DEFAULT NULL,
    PRIMARY KEY (USER_ID)
);

CREATE TABLE IF NOT EXISTS PRODUCT (
    PRODUCT_ID    INTEGER(8) NOT NULL AUTO_INCREMENT,
    PROD_NAME     VARCHAR(50) NOT NULL,
    PROD_MFCTR    VARCHAR(35) DEFAULT NULL,
    PROD_MODEL    VARCHAR(35) DEFAULT NULL,
    PROD_DESC     MEDIUMTEXT DEFAULT NULL,
    PROD_PICT_URL VARCHAR(100) NOT NULL,
    PRIMARY KEY (PRODUCT_ID)
);

/* Create database for session storage. */
CREATE DATABASE IF NOT EXISTS SESSION_STORE;
